options:
  overworld:
    health: 20
  nether:
    health: 16
    ores:
      rate:
        coal: 20
        iron: 8
        gold: 4
        redstone: 9
        lapis: 3
        diamond: 1
      size:
        coal: 6
        iron: 4
        gold: 7
        redstone: 6
        lapis: 3
        diamond: 4
  end:
    health: 40
    ores:
      rate:
        coal: 20
        iron: 5
        gold: 4
        redstone: 9
        lapis: 3
        diamond: 2
      size:
        coal: 6
        iron: 5
        gold: 4
        redstone: 6
        lapis: 3
        diamond: 4
players:
  overworld: []
  nether: []
  end: []
